### ISSUE TITLE
Crash on SSP world load

### ISSUE THREAD

**Issue by MakeLord** [Chicken-Bones/EnderStorage#36] opened 2015-04-11 22:33 UTC
Hi. While trying to load a ssp world i get this crash http://pastebin.com/j9xc1Cy3
Any help?

Forge version: 1.7.10-10.13.3.1369
ES version: 1.4.6.31
CCC version: 1.0.4.35

**Comment by Tsunayoshi** [comment] 2015-04-11 23:02
Same problem here. Maybe it is caused by the last changes in forge:
Build 1.7.10-10.13.3.1369-1.7.10:
	cpw: And handle the null case in the constructor itself. Closes #1794 (again)

Build 1.7.10-10.13.3.1368-1.7.10:
	cpw: Fix NPE - Closes #1794

Build 1.7.10-10.13.3.1367-1.7.10:
	cpw:
		Fluids are now tracked internally by mod. This allows for the server and the world to specify a "default"
		in the case of a possible alternative fluid implementation. If you always called registerFluid, things
		should work pretty seamlessly, but if you didn't (gating with an isFluidRegistered check for example)
		you should change to register anyway. This way, even if you're not default in the overall instance, you may
		become default if you're the only mod present on a server, for example, or in a world save.
		
		This should radically decrease the mixups caused by mod load ordering problems, and other issues around fluid
		tracking.

**Comment by erkro1** [comment] 2015-04-12 09:57
It's defenitely the new Forge, it has some fluid changes.

**Comment by Tsunayoshi** [comment] 2015-04-12 10:56
Yeah have trouble with forestry and railcraft, too

**Comment by erkro1** [comment] 2015-04-12 11:18
@Tsunayoshi It should be fixed in latest Forestry build ( http://ic2api.player.to:8080/job/Forestry_Dev/528/ )

**Comment by Chicken-Bones** [comment] 2015-04-17 07:08
Duplicate of #35

**Closed by Chicken-Bones** 2015-04-17 07:08 UTC
