### ISSUE TITLE
endertank rendering crashes server

### ISSUE THREAD

**Issue by ProfDeCube** [Chicken-Bones/EnderStorage#37] opened 2015-04-13 02:59 UTC
I've been making my own pack and everything else seems fine, whenever the endertank is rendered it crashes http://pastebin.com/ArM7tABY

**Comment by sci4me** [comment] 2015-04-13 04:56
I think this is the one you have? http://pastebin.com/kVi3xUYe

This needs to be fixed! Seriously!

**Comment by Chicken-Bones** [comment] 2015-04-17 07:08
Duplicate of #35

**Closed by Chicken-Bones** 2015-04-17 07:08 UTC
